using DocumentFormat.OpenXml.Drawing.Charts;
using EmployeeDAA.Core.Domain;
using EmployeeDAA.Core.Domain.Orders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EmployeeDAA.Data.Migrations
{
    [MigrationInfo("2024-02-08 13:55:00", "Initialize Order related Schema")]
    public class OrdersMigration : FluentMigrator.Migration
    {
        public override void Down()
        {

        }

        public override void Up()
        {
            Create
               .Table(nameof(OrderInfo)).WithDescription("Order details")
               .WithColumn(nameof(OrderInfo.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
               .WithColumn(nameof(OrderInfo.CustomerId)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Customer Id")
               .WithColumn(nameof(OrderInfo.CustomerName)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Order name")
               .WithColumn(nameof(OrderInfo.DateOfBirth)).AsDate().Nullable().WithColumnDescription("Date of Birth")
               .WithColumn(nameof(OrderInfo.MobileNo)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Mobile number")
               .WithColumn(nameof(OrderInfo.EmailAddress)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Email address")
               .WithColumn(nameof(OrderInfo.UnitNo)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Unit number")
               .WithColumn(nameof(OrderInfo.Block)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Block")
               .WithColumn(nameof(OrderInfo.Street)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Street")
               .WithColumn(nameof(OrderInfo.BuildingName)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Building name")
               .WithColumn(nameof(OrderInfo.Country)).AsCustom("varchar(max)").Nullable().WithColumnDescription("Country")
               .WithColumn(nameof(OrderInfo.PostalCode)).AsInt32().Nullable().WithColumnDescription("Postal code")
               .WithColumn(nameof(OrderInfo.FinalAmount)).AsCustom("decimal(18,2)").Nullable().WithColumnDescription("Final order amount")
               .WithColumn(nameof(OrderInfo.DiscountAmount)).AsCustom("decimal(18,2)").Nullable().WithColumnDescription("Discount amount")
               .WithColumn(nameof(OrderInfo.TotalPayableAmount)).AsCustom("decimal(18,2)").Nullable().WithColumnDescription("Total payable amount")
               .WithColumn(nameof(OrderInfo.PaymentOption)).AsAnsiString(50).Nullable().WithColumnDescription("payment option")
               .WithColumn(nameof(OrderInfo.OrderDate)).AsDateTime().Nullable().WithColumnDescription("Date and time of the order");
         
            Create
                .Table(nameof(OrderCart)).WithDescription("Products for an order")
                .WithColumn(nameof(OrderCart.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(OrderCart.OrderId)).AsInt32().ForeignKey(nameof(OrderInfo), nameof(OrderInfo.Id)).NotNullable().WithColumnDescription("Foreign key referencing the Order table")
                .WithColumn(nameof(OrderCart.ProductId)).AsInt32().ForeignKey(nameof(Product), nameof(Product.Id)).NotNullable().WithColumnDescription("Foreign key referencing the Product table")
                .WithColumn(nameof(OrderCart.Quantity)).AsInt32().Nullable().WithColumnDescription("Total Quantity")
                .WithColumn(nameof(OrderCart.UnitPrice)).AsCustom("decimal(18,2)").Nullable().WithColumnDescription("Unit Price")
                .WithColumn(nameof(OrderCart.TotalPrice)).AsCustom("decimal(18,2)").Nullable().WithColumnDescription("Total amount");


        }
    }
}
