using EmployeeDAA.Core.Domain.Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EmployeeDAA.Data.Migrations
{
    [MigrationInfo("2024-02-05 16:25:00", "Add Settings")]

    public class SettingsMigration : FluentMigrator.Migration
    {
        public override void Down()
        {
            throw new NotImplementedException();
        }

        public override void Up()
        {
            Create
                .Table(nameof(Settings)).WithDescription("Setting cms")
                .WithColumn(nameof(Settings.Id)).AsInt32().PrimaryKey().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(Settings.Key)).AsAnsiString(100).NotNullable().WithColumnDescription("Key for setting")
                .WithColumn(nameof(Settings.Value)).AsAnsiString(250).Nullable().WithColumnDescription("value for setting");
        }
    }
}
